window.DMC_PAGES=window.DMC_PAGES||{};
const FPI_STANDARD_KEY="dmc_production_standards", FPI_RECORD_KEY="dmc_finished_product_records", FPI_LEDGER_KEY="dmc_inventory_ledger_entries";

function pRead(key, fallback = []) { try { const v=JSON.parse(localStorage.getItem(key)); return Array.isArray(v)?v:fallback; } catch { return fallback; } }
function pWrite(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
function pEsc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function pNum(v){const n=Number(v);return Number.isFinite(n)?n:0;}
function pId(prefix){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;}
function pShow(message,type="success",title="Saved"){ if(window.DMC_SHOW_MODAL){window.DMC_SHOW_MODAL({type,title,message,confirmLabel:"OK"});} else alert(message); }
function pOptions(values, selected="", placeholder="Select"){return `<option value="">${placeholder}</option>${values.map(v=>`<option value="${pEsc(v)}" ${v===selected?"selected":""}>${pEsc(v)}</option>`).join("")}`;}
function pSettings(){try{return JSON.parse(localStorage.getItem("dmc_inventory_settings"))||window.DMC_DATA?.settings||{};}catch{return window.DMC_DATA?.settings||{};}}
function pNames(values){return (values||[]).map(v=>typeof v==="string"?v:v?.name).filter(Boolean);}

function fpiStandards(){return pRead(FPI_STANDARD_KEY,[]).filter(x=>x.active!==false);}
function fpiRefresh(){window.DMC_PAGES["finished-product-input"].content=fpiContent();renderPage("finished-product-input");}
function fpiContent(){const s=fpiStandards(),r=pRead(FPI_RECORD_KEY,[]);return `<style>.fpi-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}@media(max-width:800px){.fpi-grid{grid-template-columns:1fr}}</style><section class="panel"><div class="panel-header"><div><h3>Finished Product Input</h3><p>Enter actual production facts. Expected yield is calculated later in Production Report.</p></div><span class="badge">${r.length} Submitted</span></div><div class="instruction-box"><strong>Manager enters only:</strong><span>Product, raw material used, raw material waste, actual yield, manager, and notes.</span></div><form id="fpi-form" class="form-grid"><label>Production Date<input id="fpi-date" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>Finished Product<select id="fpi-product" required><option value="">Select product</option>${s.map(x=>`<option value="${x.standardId}">${pEsc(x.productName)}</option>`).join('')}</select></label><label>Raw Material Used<input id="fpi-raw" type="number" min="0.0001" step="any" required></label><label>Raw Material Waste<input id="fpi-waste" type="number" min="0" step="any" required value="0"></label><label>Actual Yield<input id="fpi-yield" type="number" min="0" step="any" required></label><label>Manager / Produced By<input id="fpi-manager" required></label><label class="form-full">Notes<textarea id="fpi-notes" rows="3"></textarea></label><div class="form-actions form-full"><button class="primary-button">Submit Finished Product</button></div></form></section><section class="panel"><div class="panel-header"><div><h3>Recent Submissions</h3></div></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Product</th><th>Raw Material</th><th>Waste</th><th>Actual Yield</th><th>Manager</th></tr></thead><tbody>${r.length?[...r].reverse().slice(0,10).map(x=>`<tr><td>${pEsc(x.productionDate)}</td><td>${pEsc(x.productName)}</td><td>${x.rawMaterialUsed} ${pEsc(x.rawMaterialUnit)}</td><td>${x.rawMaterialWaste} ${pEsc(x.rawMaterialUnit)}</td><td>${x.actualYield} ${pEsc(x.yieldUnit)}</td><td>${pEsc(x.manager)}</td></tr>`).join(''):'<tr><td colspan="6">No finished-product submissions yet.</td></tr>'}</tbody></table></div></section>`;}
function setupFinishedProductInputEvents(){document.getElementById('fpi-form')?.addEventListener('submit',e=>{e.preventDefault();const standard=fpiStandards().find(x=>x.standardId===document.getElementById('fpi-product').value);if(!standard)return pShow('Select a valid Production Standard.','warning','Product Required');const raw=pNum(document.getElementById('fpi-raw').value),waste=pNum(document.getElementById('fpi-waste').value),actual=pNum(document.getElementById('fpi-yield').value);if(raw<=0||waste<0||waste>raw||actual<0)return pShow('Check the raw material, waste, and actual yield values.','warning','Invalid Values');const now=new Date().toISOString(),record={recordId:pId('FPI'),productionDate:document.getElementById('fpi-date').value,submittedAt:now,standardId:standard.standardId,linkedItemId:standard.linkedItemId,productName:standard.productName,primaryRawMaterialId:standard.primaryRawMaterialId,primaryRawMaterialName:standard.primaryRawMaterialName,rawMaterialUsed:raw,rawMaterialWaste:waste,rawMaterialUnit:standard.rawMaterialUnit,actualYield:actual,yieldUnit:standard.yieldUnit||standard.baseUnit,manager:document.getElementById('fpi-manager').value.trim(),notes:document.getElementById('fpi-notes').value.trim(),standardRawMaterialQty:standard.standardRawMaterialQty,standardExpectedYield:standard.expectedYield};const records=pRead(FPI_RECORD_KEY,[]);records.push(record);pWrite(FPI_RECORD_KEY,records);const ledger=pRead(FPI_LEDGER_KEY,[]);ledger.push({entryId:pId('LED'),batchId:record.recordId,date:record.productionDate,submittedAt:now,itemId:record.linkedItemId,itemName:record.productName,quantity:record.actualYield,unit:record.yieldUnit,movementType:'Production In',movementField:'finishedProductOutput',stockEffect:'add',location:'Commissary',department:'Commissary',source:'Finished Product Input',destination:'Commissary Stock',performedBy:record.manager,notes:record.notes});pWrite(FPI_LEDGER_KEY,ledger);pShow('Finished product submitted and added to Commissary Stock.');fpiRefresh();});}
window.DMC_PAGES['finished-product-input']={eyebrow:'Commissary',title:'Finished Product Input',description:'Record raw material used, raw material waste, and actual finished-product yield.',content:fpiContent(),setup:setupFinishedProductInputEvents};
