window.DMC_PAGES=window.DMC_PAGES||{};
const PR_KEY="dmc_finished_product_records";

function pRead(key, fallback = []) { try { const v=JSON.parse(localStorage.getItem(key)); return Array.isArray(v)?v:fallback; } catch { return fallback; } }
function pWrite(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
function pEsc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function pNum(v){const n=Number(v);return Number.isFinite(n)?n:0;}
function pId(prefix){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;}
function pShow(message,type="success",title="Saved"){ if(window.DMC_SHOW_MODAL){window.DMC_SHOW_MODAL({type,title,message,confirmLabel:"OK"});} else alert(message); }
function pOptions(values, selected="", placeholder="Select"){return `<option value="">${placeholder}</option>${values.map(v=>`<option value="${pEsc(v)}" ${v===selected?"selected":""}>${pEsc(v)}</option>`).join("")}`;}
function pSettings(){try{return JSON.parse(localStorage.getItem("dmc_inventory_settings"))||window.DMC_DATA?.settings||{};}catch{return window.DMC_DATA?.settings||{};}}
function pNames(values){return (values||[]).map(v=>typeof v==="string"?v:v?.name).filter(Boolean);}

window.PR_FROM=window.PR_FROM||"";window.PR_TO=window.PR_TO||"";window.PR_PRODUCT=window.PR_PRODUCT||"";
function prRows(){return pRead(PR_KEY,[]).map(x=>{const expected=x.standardRawMaterialQty>0?(x.rawMaterialUsed/x.standardRawMaterialQty)*x.standardExpectedYield:0;const variance=x.actualYield-expected;return {...x,expectedYield:expected,variance,efficiency:expected>0?(x.actualYield/expected)*100:0,wasteRate:x.rawMaterialUsed>0?(x.rawMaterialWaste/x.rawMaterialUsed)*100:0};}).filter(x=>(!window.PR_FROM||x.productionDate>=window.PR_FROM)&&(!window.PR_TO||x.productionDate<=window.PR_TO)&&(!window.PR_PRODUCT||x.standardId===window.PR_PRODUCT));}
function prRefresh(){window.DMC_PAGES['production-report'].content=prContent();renderPage('production-report');}
function prContent(){const all=pRead(PR_KEY,[]),rows=prRows(),products=[...new Map(all.map(x=>[x.standardId,x])).values()],expected=rows.reduce((a,x)=>a+x.expectedYield,0),actual=rows.reduce((a,x)=>a+x.actualYield,0),waste=rows.reduce((a,x)=>a+x.rawMaterialWaste,0);return `<style>.pr-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:18px}.pr-card{padding:16px;border:1px solid rgba(255,255,255,.08);border-radius:12px}.pr-card strong{display:block;font-size:24px;margin-top:6px}@media(max-width:900px){.pr-summary{grid-template-columns:1fr 1fr}}</style><section class="panel"><div class="panel-header"><div><h3>Production Report</h3><p>Owner view of expected yield versus actual daily production.</p></div></div><div class="filter-grid"><label>From<input id="pr-from" type="date" value="${window.PR_FROM}"></label><label>To<input id="pr-to" type="date" value="${window.PR_TO}"></label><label>Product<select id="pr-product"><option value="">All Products</option>${products.map(x=>`<option value="${x.standardId}" ${window.PR_PRODUCT===x.standardId?'selected':''}>${pEsc(x.productName)}</option>`).join('')}</select></label><div style="align-self:end"><button class="ghost-button" id="pr-clear">Clear Filters</button></div></div></section><div class="pr-summary"><div class="pr-card"><span>Batches</span><strong>${rows.length}</strong></div><div class="pr-card"><span>Expected Yield</span><strong>${expected.toFixed(2)}</strong></div><div class="pr-card"><span>Actual Yield</span><strong>${actual.toFixed(2)}</strong></div><div class="pr-card"><span>Total Raw Waste</span><strong>${waste.toFixed(2)}</strong></div></div><section class="panel"><div class="table-wrap"><table><thead><tr><th>Date</th><th>Product</th><th>Raw Material Used</th><th>Waste</th><th>Expected</th><th>Actual</th><th>Variance</th><th>Efficiency</th><th>Waste %</th><th>Manager</th></tr></thead><tbody>${rows.length?[...rows].reverse().map(x=>`<tr><td>${pEsc(x.productionDate)}</td><td><strong>${pEsc(x.productName)}</strong></td><td>${x.rawMaterialUsed} ${pEsc(x.rawMaterialUnit)}</td><td>${x.rawMaterialWaste} ${pEsc(x.rawMaterialUnit)}</td><td>${x.expectedYield.toFixed(2)} ${pEsc(x.yieldUnit)}</td><td>${x.actualYield} ${pEsc(x.yieldUnit)}</td><td><span class="badge ${x.variance<0?'danger-badge':''}">${x.variance>=0?'+':''}${x.variance.toFixed(2)}</span></td><td>${x.efficiency.toFixed(1)}%</td><td>${x.wasteRate.toFixed(1)}%</td><td>${pEsc(x.manager)}</td></tr>`).join(''):'<tr><td colspan="10">No production records match the selected filters.</td></tr>'}</tbody></table></div></section>`;}
function setupProductionReportEvents(){document.getElementById('pr-from')?.addEventListener('change',e=>{window.PR_FROM=e.target.value;prRefresh();});document.getElementById('pr-to')?.addEventListener('change',e=>{window.PR_TO=e.target.value;prRefresh();});document.getElementById('pr-product')?.addEventListener('change',e=>{window.PR_PRODUCT=e.target.value;prRefresh();});document.getElementById('pr-clear')?.addEventListener('click',()=>{window.PR_FROM='';window.PR_TO='';window.PR_PRODUCT='';prRefresh();});}
window.DMC_PAGES['production-report']={eyebrow:'Commissary',title:'Production Report',description:'Compare raw-material-based expected yield with actual finished-product output.',content:prContent(),setup:setupProductionReportEvents};
